# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### ASSERTIONS: System Requirements
  ########################################
  assertions:
    ### Assertion: OS Version
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  ########################################
  resources:
    ########################################
    ### Initialization
    ########################################
    ########################################
    ### Install HypervisorPlatform Optional Feature
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: HypervisorPlatform
      directives:
        description: HypervisorPlatform
        allowPrerelease: true
      settings:
        Name: HypervisorPlatform
        Ensure: Present
    ### Install VirtualMachinePlatform Optional Feature
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: VirtualMachinePlatform
      directives:
        description: VirtualMachinePlatform
        allowPrerelease: true
      settings:
        Name: VirtualMachinePlatform
        Ensure: Present
    ### Install Microsoft-Windows-Subsystem-Linux Optional Feature
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: Microsoft-Windows-Subsystem-Linux
      directives:
        description: Microsoft-Windows-Subsystem-Linux
        allowPrerelease: true
      settings:
        Name: Microsoft-Windows-Subsystem-Linux
        Ensure: Present
    ########################################
    ### Install HyperV
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: hyperv 
      directives:
        description: Microsoft-Hyper-V-All 
        allowPrerelease: true
      settings:
        Name: Microsoft-Hyper-V-All 
        Ensure: Present
    ########################################
    ### Install HyperV-Tools
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: hyperv-tools 
      directives:
        description: Microsoft-Hyper-V-Tools-All 
        allowPrerelease: true
      settings:
        Name: Microsoft-Hyper-V-Tools-All 
        Ensure: Present
    ########################################
    ### Install Windows Subsystem for Linux
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wsl
      dependsOn:
        - Microsoft-Windows-Subsystem-Linux
      directives:
        description: WSL
        allowPrerelease: true
      settings:
        id: "Microsoft.WSL"
        source: winget  
    ### Install Ubuntu 22.04 LTS (WSL)
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - wsl
      directives:
        description: Ubuntu 22.04 LTS
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget 
    ########################################
    ### Install Powershell
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Powershell
      directives:
        description: Install Powershell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    ########################################
    ### Install Windows Terminal
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WindowsTerminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    ########################################
    ### Configuration
    ########################################
    ########################################
    ### Add current user to Hyper-V Administrators group
    ### -------------------------------------
    - resource: PSDscResources/Script
      id: HyperVAdminGroup
      directives:
        description: Add current user to Hyper-V Administrators group
        allowPrerelease: true
      settings:
        SetScript: |
          # Get the current user's SID
          $currentUserSid = ([System.Security.Principal.WindowsIdentity]::GetCurrent()).User.Value
          # Get the Hyper-V Administrators group
          $hyperVAdminsGroup = Get-LocalGroup -SID "S-1-5-32-578"
          # If user is already a member of the Hyper-V Administrators group, exit
          if (!(Get-LocalGroupMember -Group $hyperVAdminsGroup -Member $currentUserSid)) {
            # Add the current user to the Hyper-V Administrators group
            Add-LocalGroupMember -Group $hyperVAdminsGroup -Member $currentUserSid
          }
        GetScript: |
          return $false
        TestScript: |
          return $false
    ########################################
