# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### ASSERTIONS: System Requirements
  ########################################
  assertions:
    ### Assertion: OS Version
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  ########################################
  resources:
    ########################################
    ### Initialization
    ########################################
    ########################################
    ### Install HypervisorPlatform Optional Feature
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: HypervisorPlatform
      directives:
        description: HypervisorPlatform
        allowPrerelease: true
      settings:
        Name: HypervisorPlatform
        Ensure: Present
    ### Install VirtualMachinePlatform Optional Feature
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: VirtualMachinePlatform
      directives:
        description: VirtualMachinePlatform
        allowPrerelease: true
      settings:
        Name: VirtualMachinePlatform
        Ensure: Present
    ########################################
    ### Install HyperV
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: hyper-v 
      directives:
        description: Microsoft-Hyper-V-All 
        allowPrerelease: true
      settings:
        Name: Microsoft-Hyper-V-All 
        Ensure: Present
    ########################################
    ### Install HyperV-Tools
    ### -------------------------------------
    - resource: PSDscResources/WindowsOptionalFeature
      id: hyperv-tools 
      directives:
        description: Microsoft-Hyper-V-All 
        allowPrerelease: true
      settings:
        Name: Microsoft-Hyper-V-Tools-All 
        Ensure: Present
    ########################################
    ### Install Windows Subsystem for Linux
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: wsl
      directives:
        description: WSL
        allowPrerelease: true
      settings:
        id: Microsoft.WSL
        source: winget  
    ### Install Ubunti 22.04 LTS (WSL)
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - wsl
      directives:
        description: Ubuntu 22.04 LTS
        allowPrerelease: true
      settings:
        id: Canonical.Ubuntu.2204
        source: winget 
