# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### ASSERTIONS: System Requirements
  ########################################
  assertions:
    ### Assertion: OS Version
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  ########################################
  resources:
    ########################################
    ### Initialization
    ########################################
    ########################################
    ### Create workspace directory
    ### -------------------------------------
    - resource: File
      id: workspacedir
      directives:
        description: Create workspace directory
        module: PSDesiredStateConfiguration
        allowPrerelease: true
      settings:
        Ensure: Present
        Type: Directory
        DestinationPath: $env:USERPROFILE\workspace
    ### Install Git
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    ### Clone dotfiles repository
    ### -------------------------------------
    - resource: GitDsc/GitClone
      id: mydotfiles
      dependsOn:
        - git
        - workspacedir
      directives:
        description: Clone my dotfiles GitHub repository
        allowPrerelease: true
      settings:
        HttpsUrl: https://github.com/abrioso/dotfiles-windows
        RootDirectory: $env:USERPROFILE\workspace
        Ensure: Present
    ### Enable: Developer Mode
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
     ### Show file extensions and hidden files
     ### -------------------------------------
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Show File Extensions and hidden files
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
    ### Set theme to Dark
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Set theme to Dark
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true
    ########################################
    ### Install CLIs, SDKs & Tools
    ########################################
    ### Install DevHome
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: DevHome
      directives:
        description: Install DevHome
        allowPrerelease: true
      settings:
        id: Microsoft.DevHome
        source: winget
    ### Install DevHome Azure Extension
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - DevHome
      directives:
        description: Install DevHome Azure Extension
        allowPrerelease: true
      settings:
        id: 9MV8F79FGXTR
        source: msstore
    ### Install DevHome GitHub Extension
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - DevHome
      directives:
        description: Install DevHome GitHub Extension
        allowPrerelease: true
      settings:
        id: 9NZCC27PR6N6
        source: msstore
    ### Install Powershell
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Powershell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    ### Install OMP
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OMP
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    ### Install Azure CLI
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azurecli
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
       id:  Microsoft.AzureCLI
       source: winget
    ### Install Azd
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azd
        allowPrerelease: true
      settings:
        id: Microsoft.Azd
        source: winget
    ### Install Visual Studio Code
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Microsoft Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        ensure: Present
    ########################################
    ### Configure settings
    ########################################
    ### Git Configure Name
    ### -------------------------------------
    - resource: GitDsc/GitConfigUserName
      directives:
        description: Configure Git
        allowPrerelease: true
      dependsOn:
        - git
      settings:
         UserName: "Andre Kakoo Brioso"
         ConfigLocation: "Global"
    ### WORKAROUND: GitDsc/GitConfigUserName not working right now.
    ### Git Configure Name
    ### -------------------------------------
    - resource: PSDscResources/Script
      dependsOn:
        - git
      directives:
        description: Configure Git to use Default WAM account
      settings:
        SetScript: |
          git config --global user.name "Andre Kakoo Brioso"
        GetScript: return $false
        TestScript: return $false
    ### Git Configure Email
    ### -------------------------------------
    - resource: GitDsc/GitConfigUserEmail
      directives:
        description: Configure Git
        allowPrerelease: true
      dependsOn:
        - git
      settings:
         UserEmail: "akbrioso@iseg.ulisboa.pt"
         ConfigLocation: "Global"
    ### Configure Git to use Default WAM account
    ### -------------------------------------
    - resource: PSDscResources/Script
      dependsOn:
        - git
      directives:
        description: Configure Git to use Default WAM account
      settings:
        SetScript: |
          git config --global credential.msauthUseDefaultAccount true
        GetScript: return $false
        TestScript: return $false
    ### Install VS Code Extensions
    ### -------------------------------------
    - resource: PSDscResources/Script
      id: vscodeextensions
      dependsOn:
        - vscode
      directives:
        description: Install Python Extension for VS Code
      settings:
        SetScript: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
          code --install-extension github.copilot
          code --install-extension devcenter.ms-devbox
          code --install-extension ms-vscode.powershell
          code --install-extension ms-dotnettools.csdevkit
          code --install-extension ms-azuretools.azure-dev
        GetScript: return $false
        TestScript: return $false
    ### Install Edge
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: edge
      directives:
        description: Install Edge
        allowPrerelease: true
      settings:
        id: Microsoft.Edge
        source: winget