<#
.SYNOPSIS
    Deploys per-machine PowerShell profiles using a OneDrive-safe stub layout.

.DESCRIPTION
    On Entra ID joined machines with OneDrive Known Folder Move, the Documents
    folder (and therefore $PROFILE) is synchronised across devices, so profiles
    stored there get overwritten by whichever machine synced last.

    This module keeps the real profile content local and personal:

    1. Copies each .ps1 from the repository 'powershell-profiles' directory into
       '$env:LOCALAPPDATA\dotfiles\powershell-profiles' (never OneDrive-synced).
       Files are only rewritten when their content actually changed.
    2. Writes a small marker stub into the active PowerShell profile directory
       ($PROFILE parent) that dot-sources the local copy. The stub carries a
       dotfiles marker line so reruns can safely refresh it.

    Safety rules:
    - An existing regular file WITHOUT the dotfiles marker is left untouched to
      avoid destroying user-authored profiles.
    - A leftover symlink from previous setup versions is replaced by the stub.
    - Fully idempotent: unchanged copies and correct stubs are skipped.

    This module does not require elevation.
#>

$dotfileRootDir = Split-Path -Parent $PSScriptRoot

. "$dotfileRootDir\setup-scripts\setup-functions.ps1"

$dateTime = Get-Date -Format "yyyyMMdd-HHmmss"
$logDir = Join-Path $dotfileRootDir "logs"
$scriptName = Split-Path -Leaf $PSCommandPath
$logFile = "$logDir/$scriptName-$dateTime.txt"

Start-Logging -LogFilePath $logFile

$stubMarker = '# dotfiles-managed stub - real profile lives in LOCALAPPDATA. Do not edit this file.'

try {
    $profilesSource = Join-Path $dotfileRootDir "powershell-profiles"
    if (-not (Test-Path -LiteralPath $profilesSource -PathType Container)) {
        Write-ErrorMessage "Powershell profiles source directory not found: $profilesSource"
        Stop-Logging
        Exit 1
    }

    $profileFiles = @(Get-ChildItem -Path $profilesSource -Filter "*.ps1" -File)
    if ($profileFiles.Count -eq 0) {
        Write-WarningMessage "No .ps1 profile files found in: $profilesSource"
        Stop-Logging
        Exit 0
    }

    # 1. Mirror the repo profiles into a machine-local store under LOCALAPPDATA.
    $localStore = Join-Path $env:LOCALAPPDATA "dotfiles\powershell-profiles"
    if (-not (Test-Path -LiteralPath $localStore)) {
        Write-Info "Creating local profile store: $localStore"
        New-Item -ItemType Directory -Path $localStore -Force | Out-Null
    }

    foreach ($profileFile in $profileFiles) {
        $localCopy = Join-Path $localStore $profileFile.Name
        $needsCopy = $true

        if (Test-Path -LiteralPath $localCopy) {
            $existingHash = (Get-FileHash -LiteralPath $localCopy -Algorithm SHA256).Hash
            $sourceHash = (Get-FileHash -LiteralPath $profileFile.FullName -Algorithm SHA256).Hash
            if ($existingHash -eq $sourceHash) {
                Write-Info "Local copy of '$($profileFile.Name)' is up to date. Skipping."
                $needsCopy = $false
            }
        }

        if ($needsCopy) {
            Write-Info "Copying '$($profileFile.Name)' to $localStore"
            Copy-Item -LiteralPath $profileFile.FullName -Destination $localCopy -Force
        }
    }

    # 2. Replace whatever is in the (possibly OneDrive-synced) profile directory
    #    with a small stub that dot-sources the machine-local copy.
    $profileDirectory = Split-Path -Parent $PROFILE
    if (-not (Test-Path -LiteralPath $profileDirectory)) {
        Write-Info "Creating PowerShell profile directory: $profileDirectory"
        New-Item -ItemType Directory -Path $profileDirectory -Force | Out-Null
    }

    foreach ($profileFile in $profileFiles) {
        $targetPath = Join-Path $profileDirectory $profileFile.Name
        $stubContent = @(
            $stubMarker
            ". `"$localStore\$($profileFile.Name)`""
            ''
        ) -join [Environment]::NewLine

        $action = $null
        if (Test-Path -LiteralPath $targetPath) {
            $existingItem = Get-Item -LiteralPath $targetPath -Force

            if ($existingItem.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                # Legacy symlink from earlier setup versions - safe to replace.
                Write-Info "Removing legacy symlink at '$targetPath'."
                Remove-Item -LiteralPath $targetPath -Force
                $action = 'create'
            } elseif ((Get-Content -LiteralPath $targetPath -TotalCount 1 -ErrorAction SilentlyContinue) -eq $stubMarker) {
                $existingStub = Get-Content -LiteralPath $targetPath -Raw
                if ($existingStub -eq $stubContent) {
                    Write-Info "Stub for '$($profileFile.Name)' is already correct. Skipping."
                } else {
                    Write-Info "Refreshing outdated stub for '$($profileFile.Name)'."
                    $action = 'create'
                }
            } else {
                Write-WarningMessage "'$($profileFile.Name)' exists as a user-authored file without the dotfiles marker. Skipping to avoid data loss."
            }
        } else {
            $action = 'create'
        }

        if ($action -eq 'create') {
            Write-Info "Writing stub: $targetPath -> $localStore\$($profileFile.Name)"
            Set-Content -LiteralPath $targetPath -Value $stubContent -Encoding UTF8 -NoNewline
        }
    }

    Exit 0
}
catch {
    Write-ErrorMessage "Failed to deploy local PowerShell profiles: $($_.Exception.Message)"
    Stop-Logging
    Exit 1
}
